Kafka Source & Kafka Target - Add tlsEnable parameter
triggermesh/triggermesh pull request #1017
Opened 2022-07-06 15:04 UTC by FranBarrera

2022-07-06 15:26 UTC, cab105 requested changes
Thank you for adding in the `tlsEnable` component. The wait group implementation is not correct, and will result in buggy behavior.

2022-07-06 17:59 UTC, cab105 commented on pkg/sources/adapter/kafkasource/adapter.go
> +	go func() {
So if I understand this:
1. Start function is invoked when the sources starts up
2. Spawn a new thread
2a. Inside this new thread, loop continuously and process messages as they are received
3. Block until we receive a response from the new thread of `nil` or `err`

At this point, switching from wait groups to channels doesn't yield anything as this is still "single threaded," but with the caveat that a new thread has been spun up to process the messages. Normally, it'd be best to spawn the processing in a separate thread, and provide callback handle that can be used to stop processing of all other threads.

2022-07-06 18:40 UTC, cab105 commented on pkg/sources/adapter/kafkasource/adapter.go
> +	go func() {
It is, but that's not what is implemented.

What @FranBarrera has is closer to:
```
start routine:
  fork:
    // child
    loop:
      err := dosomething()
      return err

  // parent
  block for response
  return result
```

In this case, the for loop is effectively ignored, and we're spawning a thread to do a single task, which I highly doubt is the intent.

2022-07-06 20:04 UTC, cab105 approved these changes
Much better. Left a minor nit. Also, will you be rerunning `make codegen` to regenerate the client/deepcopy files?

Providing a conditional approval pending the above get resolved.

2022-07-06 20:04 UTC, cab105 commented on config/300-kafkasource.yaml
> +                - tlsEnable
Should be okay to make this optional. Just so long as `omitempty` is set on the type.

2022-07-06 20:04 UTC, cab105 commented on config/301-kafkatarget.yaml
> +                - tlsEnable
Should be okay to make this optional. Just so long as omitempty is set on the type.

2022-07-07 08:56 UTC, odacremolbap approved these changes

2022-07-07 09:12 UTC, merged