Update Repo Documentation for Google Cloud Pub Sub Target
triggermesh/triggermesh pull request #1084
Opened 2022-08-22 16:18 UTC by JeffNeff

2022-08-23 05:39 UTC, tzununbekov requested changes

2022-08-23 05:39 UTC, tzununbekov commented on docs/targets/googlecloudpubsub.md
> +# Event Target for Google Cloud Pub Sub
Here and below: the product name is "Google Cloud **Pub/Sub**", so let's stick to it.

```suggestion
# Event Target for Google Cloud Pub/Sub
```

2022-08-23 05:39 UTC, tzununbekov commented on docs/targets/googlecloudpubsub.md
> +- a pre-existing Google Cloud Pub Sub Topic.
Consistent styling:
```suggestion
- A pre-existing Google Cloud Pub/Sub Topic.
```

2022-08-23 05:39 UTC, tzununbekov commented on docs/targets/googlecloudpubsub.md
> +1. [Clone][clone] the Triggermesh mono repo and navigate to the example manifest located in the [`triggermesh/config/samples/targets/googlecloudpubsub/`][sample-manifest] section of the Triggermesh m
Here and below - camel casing:
```suggestion
1. [Clone][clone] the TriggerMesh mono repo and navigate to the example manifest located in the [`triggermesh/config/samples/targets/googlecloudpubsub/`][sample-manifest] section of the TriggerMesh mono repo.
```

2022-08-23 05:39 UTC, tzununbekov commented on docs/targets/googlecloudpubsub.md
> +1. [Clone][clone] the Triggermesh mono repo and navigate to the example manifest located in the [`triggermesh/config/samples/targets/googlecloudpubsub/`][sample-manifest] section of the Triggermesh m
Can we also replace `mono repo` with something that does not expose unnecessary technical details of the project? We never used the term `mono repo` for user-facing docs.

2022-08-23 05:39 UTC, tzununbekov commented on docs/targets/googlecloudpubsub.md
> +[ce-jsonformat]: https://github.com/cloudevents/spec/blob/v1.0/json-format.md
Not used.

2022-09-06 07:46 UTC, jmcx commented
can we archive this? I think we already pushed the doc to the doc website

2023-01-16 09:54 UTC, closed without merging