Create a Simple Adapter Test For AWSSQS Target
triggermesh/triggermesh pull request #483
Opened 2022-01-21 14:35 UTC by JeffNeff

2022-01-25 17:50 UTC, antoineco requested changes
A good start.
The test needs a few improvements to become really useful (e.g. we should at the very least assert the generated data).

2022-01-25 17:50 UTC, antoineco commented on pkg/targets/adapter/awssqstarget/adapter_test.go
> +				awsArnString:     "arn:aws:kinesis:us-east-1:123456789012:stream/foo",
Kinesis?

2022-01-25 17:50 UTC, antoineco commented on pkg/targets/adapter/awssqstarget/adapter_test.go
> +func (c *standardMockSQSClient) SendMessage(*sqs.SendMessageInput) (*sqs.SendMessageOutput, error) {
To make the test more useful than "failed / didn't fail", we could make the mock client record the input parameter here, and assert that it conforms to what the target should do.

Some inspiration:
https://github.com/triggermesh/triggermesh/blob/54652bfd317467ece28dcf1f6f6a3269d1b94a3e/pkg/targets/adapter/splunktarget/adapter_test.go#L39

2022-01-26 13:55 UTC, JeffNeff commented on pkg/targets/adapter/awssqstarget/adapter_test.go
>  	sync.Mutex
yes. its copy pasta from your source test.

2022-01-26 14:46 UTC, JeffNeff commented on pkg/targets/adapter/awssqstarget/adapter_test.go
> +		},
That would greatly complicate the tests.. as we would have to retrieve the message from a Queue to verify this. If we want it, i will do it tho.

2022-01-26 14:47 UTC, JeffNeff commented on pkg/targets/adapter/awssqstarget/adapter_test.go
> +			if event != nil {
Im sorry... but i dont understand :/

2022-01-26 21:38 UTC, antoineco commented on pkg/targets/adapter/awssqstarget/adapter_test.go
> +			if event != nil {
You don't check what your test actually expects an event or not, you simply check for `nil` and assumes something based on that.

The correct approach should read as:
- if a expect an event but got `nil`, something is wrong
- if I don't expect an event but got one, something is wrong

**not**

- if I got an event, I probably should have gotten an event

2022-01-27 00:46 UTC, cab105 commented on pkg/targets/adapter/awssqstarget/adapter_test.go
> +		},
Yup

2022-01-27 00:52 UTC, antoineco requested changes
The input recorder that was just added isn't even used, so I'm not certain what feedback you want to hear by asking another review from me.

We should record calls to SendMessage by appending to it, then assert that calls to SendMessage contained messages in the expected shape. That's it.

2022-01-27 16:38 UTC, antoineco commented
@JeffNeff the **number** of created message is asserted, but this doesn't tell us anything about the SQS message generated by the application.
Enforcing expectations on the data itself is the single most important thing we want to get from this test (because that's what the adapter is for), otherwise we can rename it to "Test that we are sending only one request pretty per incoming event".

I'm thinking about things like
- checking that the data is passed unmodified to the message body
- if CloudEvents context attributes should be propagated to the attributes of the SQS message (not sure if that was part of the requirement when we wrote the target), assert that they are
- etc.

In short, look at what the adapter's code seems to be doing with the incoming event, and ensure the outgoing message is conformant.

2022-06-02 16:18 UTC, closed without merging