Remove `spec.public` attribute from Function
triggermesh/triggermesh pull request #814
Opened 2022-05-01 13:57 UTC by antoineco

It is now redundant with [`spec.adapterOverrides.public`](https://github.com/triggermesh/triggermesh/blob/8eb93f5ee32c559bce379c1e4d74b6e0d57c8044/config/303-function.yaml#L60-L66).

2022-05-01 15:38 UTC, sebgoa approved these changes

2022-05-02 04:38 UTC, tzununbekov requested changes
Please update [Python](https://github.com/triggermesh/triggermesh/blob/main/config/samples/functions/python.yaml#L22) and [Ruby](https://github.com/triggermesh/triggermesh/blob/main/config/samples/functions/ruby.yaml#L21) samples accordingly

2022-05-02 05:50 UTC, tzununbekov commented on config/samples/functions/python.yaml
>    responseIsEvent: true
well, I not exactly what I meant 😅
let's have one sample function public 

```suggestion
  responseIsEvent: true
  adapterOverrides:
    public: true
```

2022-05-02 07:57 UTC, tzununbekov approved these changes

2022-05-02 08:23 UTC, merged